### ISSUE TITLE
Demo request

### ISSUE THREAD

**Issue by ares** [joeyloman/foreman_openshift_ansible_inventory#1]
Hello,

I randomly came across this project and it seems you have interesting use case for Foreman. It would be great if more people knew about how you deploy openshift using Foreman as an inventory. Would you be interested in presenting this on our Foreman community demo?

Thanks, please feel free to close this issue, I didn't know how better I could reach out.

**Comment by joeyloman** [comment]
Hi Marek,
Thanks for contacting me. Since we both work at Red Hat, I will contact you internally about this :-)
